
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Controls
{
	public partial class FeedbackDialog
	{
		private global::Gtk.Table tblMain;
		private global::Gtk.Label lblFeedback;
		private global::Gtk.Label lblStatus;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Controls.FeedbackDialog
			this.Name = "Moscrif.IDE.Controls.FeedbackDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Feedback");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child Moscrif.IDE.Controls.FeedbackDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tblMain = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.tblMain.Name = "tblMain";
			this.tblMain.RowSpacing = ((uint)(6));
			this.tblMain.ColumnSpacing = ((uint)(6));
			this.tblMain.BorderWidth = ((uint)(10));
			// Container child tblMain.Gtk.Table+TableChild
			this.lblFeedback = new global::Gtk.Label ();
			this.lblFeedback.Name = "lblFeedback";
			this.lblFeedback.Xalign = 0F;
			this.lblFeedback.LabelProp = global::Mono.Unix.Catalog.GetString ("Please give us a feedback.");
			this.tblMain.Add (this.lblFeedback);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblMain [this.lblFeedback]));
			w2.RightAttach = ((uint)(2));
			w2.XPadding = ((uint)(10));
			w2.YPadding = ((uint)(10));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.lblStatus = new global::Gtk.Label ();
			this.lblStatus.Name = "lblStatus";
			this.lblStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.tblMain.Add (this.lblStatus);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblMain [this.lblStatus]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			w1.Add (this.tblMain);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.tblMain]));
			w4.Position = 0;
			// Internal child Moscrif.IDE.Controls.FeedbackDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("_Send");
			w5.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 524;
			this.DefaultHeight = 316;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
