
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Controls.Wizard
{
	public partial class NewProjectWizzard_New
	{
		private global::Gtk.Notebook ntbWizzard;
		private global::Gtk.Table table2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label lblNewProject;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label lblHint;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.IconView ivSelectTyp;
		private global::Gtk.Table table3;
		private global::Gtk.Entry entrProjectName;
		private global::Moscrif.IDE.Components.FileEntry feLocation;
		private global::Gtk.Label label1;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Table table4;
		private global::Gtk.ComboBox cbTemplate;
		private global::Gtk.Entry entrPage2PrjName;
		private global::Gtk.IconView ivSelectOrientation;
		private global::Gtk.Label label2;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Table tblLibraries;
		private global::Gtk.Table tblScreens;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label9;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label lblCustom;
		private global::Gtk.Label label6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView nvOutput;
		private global::Gtk.Label label11;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button btnBack;
		private global::Gtk.Button btnNext;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Controls.Wizard.NewProjectWizzard_New
			this.Name = "Moscrif.IDE.Controls.Wizard.NewProjectWizzard_New";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Moscrif.IDE.Controls.Wizard.NewProjectWizzard_New.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.ntbWizzard = new global::Gtk.Notebook ();
			this.ntbWizzard.CanFocus = true;
			this.ntbWizzard.Name = "ntbWizzard";
			this.ntbWizzard.CurrentPage = 1;
			this.ntbWizzard.ShowBorder = false;
			this.ntbWizzard.BorderWidth = ((uint)(10));
			// Container child ntbWizzard.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(4)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblNewProject = new global::Gtk.Label ();
			this.lblNewProject.Name = "lblNewProject";
			this.lblNewProject.LabelProp = global::Mono.Unix.Catalog.GetString ("New project");
			this.hbox1.Add (this.lblNewProject);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblNewProject]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w3.XPadding = ((uint)(5));
			w3.YPadding = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblHint = new global::Gtk.Label ();
			this.lblHint.Name = "lblHint";
			this.lblHint.UseMarkup = true;
			this.lblHint.Selectable = true;
			this.hbox2.Add (this.lblHint);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblHint]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.table2.Add (this.hbox2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox2]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XPadding = ((uint)(5));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.HeightRequest = 95;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ivSelectTyp = new global::Gtk.IconView ();
			this.ivSelectTyp.HeightRequest = 25;
			this.ivSelectTyp.CanFocus = true;
			this.ivSelectTyp.Name = "ivSelectTyp";
			this.ivSelectTyp.Columns = 3;
			this.ivSelectTyp.Orientation = ((global::Gtk.Orientation)(0));
			this.scrolledwindow1.Add (this.ivSelectTyp);
			this.table2.Add (this.scrolledwindow1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.scrolledwindow1]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XPadding = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.entrProjectName = new global::Gtk.Entry ();
			this.entrProjectName.CanFocus = true;
			this.entrProjectName.Name = "entrProjectName";
			this.entrProjectName.IsEditable = true;
			this.entrProjectName.InvisibleChar = '●';
			this.table3.Add (this.entrProjectName);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.entrProjectName]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.feLocation = new global::Moscrif.IDE.Components.FileEntry ();
			this.feLocation.Name = "feLocation";
			this.feLocation.IsFolder = true;
			this.table3.Add (this.feLocation);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.feLocation]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Project Name :");
			this.table3.Add (this.label1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label1]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Location :");
			this.table3.Add (this.label3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Workspace :");
			this.table3.Add (this.label4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.label4]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table2.Add (this.table3);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.table3]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XPadding = ((uint)(5));
			w13.YPadding = ((uint)(5));
			this.ntbWizzard.Add (this.table2);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.ntbWizzard.SetTabLabel (this.table2, this.label5);
			this.label5.ShowAll ();
			// Container child ntbWizzard.Gtk.Notebook+NotebookChild
			this.table4 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.cbTemplate = global::Gtk.ComboBox.NewText ();
			this.cbTemplate.Name = "cbTemplate";
			this.table4.Add (this.cbTemplate);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4 [this.cbTemplate]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XPadding = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entrPage2PrjName = new global::Gtk.Entry ();
			this.entrPage2PrjName.CanFocus = true;
			this.entrPage2PrjName.Name = "entrPage2PrjName";
			this.entrPage2PrjName.IsEditable = true;
			this.entrPage2PrjName.InvisibleChar = '●';
			this.table4.Add (this.entrPage2PrjName);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4 [this.entrPage2PrjName]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XPadding = ((uint)(5));
			w16.YPadding = ((uint)(5));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.ivSelectOrientation = new global::Gtk.IconView ();
			this.ivSelectOrientation.CanFocus = true;
			this.ivSelectOrientation.Name = "ivSelectOrientation";
			this.ivSelectOrientation.Columns = 3;
			this.ivSelectOrientation.Orientation = ((global::Gtk.Orientation)(0));
			this.table4.Add (this.ivSelectOrientation);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4 [this.ivSelectOrientation]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XPadding = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Project Name :");
			this.table4.Add (this.label2);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4 [this.label2]));
			w18.XPadding = ((uint)(6));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Orientation :");
			this.table4.Add (this.label7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table4 [this.label7]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Template :");
			this.table4.Add (this.label8);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table4 [this.label8]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.tblLibraries = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.tblLibraries.Name = "tblLibraries";
			this.tblLibraries.RowSpacing = ((uint)(6));
			this.tblLibraries.ColumnSpacing = ((uint)(6));
			this.table4.Add (this.tblLibraries);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table4 [this.tblLibraries]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.tblScreens = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.tblScreens.Name = "tblScreens";
			this.tblScreens.RowSpacing = ((uint)(6));
			this.tblScreens.ColumnSpacing = ((uint)(6));
			this.table4.Add (this.tblScreens);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table4 [this.tblScreens]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Libraries :");
			this.vbox2.Add (this.label9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label9]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			this.table4.Add (this.vbox2);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4 [this.vbox2]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblCustom = new global::Gtk.Label ();
			this.lblCustom.Name = "lblCustom";
			this.lblCustom.Xalign = 1F;
			this.lblCustom.LabelProp = global::Mono.Unix.Catalog.GetString ("Custom :");
			this.vbox3.Add (this.lblCustom);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblCustom]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			this.table4.Add (this.vbox3);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table4 [this.vbox3]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			this.ntbWizzard.Add (this.table4);
			global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.ntbWizzard [this.table4]));
			w27.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.ntbWizzard.SetTabLabel (this.table4, this.label6);
			this.label6.ShowAll ();
			// Container child ntbWizzard.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nvOutput = new global::Gtk.NodeView ();
			this.nvOutput.CanFocus = true;
			this.nvOutput.Name = "nvOutput";
			this.GtkScrolledWindow.Add (this.nvOutput);
			this.ntbWizzard.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.ntbWizzard [this.GtkScrolledWindow]));
			w29.Position = 2;
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.ntbWizzard.SetTabLabel (this.GtkScrolledWindow, this.label11);
			this.label11.ShowAll ();
			w1.Add (this.ntbWizzard);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(w1 [this.ntbWizzard]));
			w30.Position = 0;
			// Internal child Moscrif.IDE.Controls.Wizard.NewProjectWizzard_New.ActionArea
			global::Gtk.HButtonBox w31 = this.ActionArea;
			w31.Name = "dialog1_ActionArea";
			w31.Spacing = 10;
			w31.BorderWidth = ((uint)(10));
			w31.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31 [this.buttonCancel]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnBack = new global::Gtk.Button ();
			this.btnBack.CanDefault = true;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString ("_Back");
			w31.Add (this.btnBack);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31 [this.btnBack]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnNext = new global::Gtk.Button ();
			this.btnNext.CanFocus = true;
			this.btnNext.Name = "btnNext";
			this.btnNext.UseUnderline = true;
			this.btnNext.Label = global::Mono.Unix.Catalog.GetString ("_Next");
			w31.Add (this.btnNext);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31 [this.btnNext]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 569;
			this.DefaultHeight = 383;
			this.Show ();
			this.btnBack.Clicked += new global::System.EventHandler (this.OnBtnBackClicked);
			this.btnNext.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
