
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Option
{
	public partial class EditorWidget
	{
		private global::Gtk.Table tblMain;
		private global::Gtk.Entry entrExtension;
		private global::Gtk.Frame frmExternal;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table tblExternal;
		private global::Gtk.Entry entrParameters;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tvExtension;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button btnAdd;
		private global::Gtk.Button btnDelete;
		private global::Gtk.Button btnSave;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Option.EditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Option.EditorWidget";
			// Container child Moscrif.IDE.Option.EditorWidget.Gtk.Container+ContainerChild
			this.tblMain = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.tblMain.Name = "tblMain";
			this.tblMain.RowSpacing = ((uint)(6));
			this.tblMain.ColumnSpacing = ((uint)(6));
			this.tblMain.BorderWidth = ((uint)(5));
			// Container child tblMain.Gtk.Table+TableChild
			this.entrExtension = new global::Gtk.Entry ();
			this.entrExtension.CanFocus = true;
			this.entrExtension.Name = "entrExtension";
			this.entrExtension.IsEditable = true;
			this.entrExtension.InvisibleChar = '●';
			this.tblMain.Add (this.entrExtension);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblMain [this.entrExtension]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child tblMain.Gtk.Table+TableChild
			this.frmExternal = new global::Gtk.Frame ();
			this.frmExternal.Name = "frmExternal";
			// Container child frmExternal.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.tblExternal = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tblExternal.Name = "tblExternal";
			this.tblExternal.RowSpacing = ((uint)(6));
			this.tblExternal.ColumnSpacing = ((uint)(6));
			this.tblExternal.BorderWidth = ((uint)(5));
			// Container child tblExternal.Gtk.Table+TableChild
			this.entrParameters = new global::Gtk.Entry ();
			this.entrParameters.CanFocus = true;
			this.entrParameters.Name = "entrParameters";
			this.entrParameters.IsEditable = true;
			this.entrParameters.InvisibleChar = '●';
			this.tblExternal.Add (this.entrParameters);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblExternal [this.entrParameters]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblExternal.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Program :");
			this.tblExternal.Add (this.label3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblExternal [this.label3]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblExternal.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Parameters :");
			this.tblExternal.Add (this.label4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblExternal [this.label4]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.tblExternal);
			this.frmExternal.Add (this.GtkAlignment);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>External Editor</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frmExternal.LabelWidget = this.GtkLabel3;
			this.tblMain.Add (this.frmExternal);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblMain [this.frmExternal]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child tblMain.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvExtension = new global::Gtk.TreeView ();
			this.tvExtension.WidthRequest = 175;
			this.tvExtension.CanFocus = true;
			this.tvExtension.Name = "tvExtension";
			this.GtkScrolledWindow.Add (this.tvExtension);
			this.tblMain.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblMain [this.GtkScrolledWindow]));
			w9.BottomAttach = ((uint)(5));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 6;
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAdd = new global::Gtk.Button ();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			this.btnAdd.Label = global::Mono.Unix.Catalog.GetString ("Add new");
			this.hbuttonbox2.Add (this.btnAdd);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnAdd]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.hbuttonbox2.Add (this.btnDelete);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnDelete]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbuttonbox2.Add (this.btnSave);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnSave]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.tblMain.Add (this.hbuttonbox2);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblMain [this.hbuttonbox2]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(3));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Extension :");
			this.tblMain.Add (this.label1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblMain [this.label1]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XPadding = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child tblMain.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Command :");
			this.tblMain.Add (this.label2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblMain [this.label2]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XPadding = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(6));
			this.Add (this.tblMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label1.MnemonicWidget = this.btnAdd;
			this.Hide ();
			this.btnAdd.Clicked += new global::System.EventHandler (this.OnBtnAddClicked);
			this.btnDelete.Clicked += new global::System.EventHandler (this.OnBtnDeleteClicked);
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
		}
	}
}
