
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Settings
{
	public partial class ProjectConditionsPanel
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Settings.ProjectConditionsPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Settings.ProjectConditionsPanel";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
