
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Option
{
	public partial class CompileWidget
	{
		private global::Gtk.Table table2;
		private global::Gtk.CheckButton chbClearConsole;
		private global::Gtk.CheckButton chbFirstError;
		private global::Gtk.CheckButton chbOpenOutput;
		private global::Gtk.CheckButton chbPrecompile;
		private global::Gtk.CheckButton chbSaveAfterRun;
		private global::Gtk.CheckButton chbShowError;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Option.CompileWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Option.CompileWidget";
			// Container child Moscrif.IDE.Option.CompileWidget.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.chbClearConsole = new global::Gtk.CheckButton ();
			this.chbClearConsole.CanFocus = true;
			this.chbClearConsole.Name = "chbClearConsole";
			this.chbClearConsole.Label = global::Mono.Unix.Catalog.GetString ("Clear Console before Run");
			this.chbClearConsole.Active = true;
			this.chbClearConsole.DrawIndicator = true;
			this.chbClearConsole.UseUnderline = true;
			this.table2.Add (this.chbClearConsole);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbClearConsole]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.XPadding = ((uint)(5));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chbFirstError = new global::Gtk.CheckButton ();
			this.chbFirstError.CanFocus = true;
			this.chbFirstError.Name = "chbFirstError";
			this.chbFirstError.Label = global::Mono.Unix.Catalog.GetString ("Stop Compilation on First Error");
			this.chbFirstError.Active = true;
			this.chbFirstError.DrawIndicator = true;
			this.chbFirstError.UseUnderline = true;
			this.table2.Add (this.chbFirstError);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbFirstError]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XPadding = ((uint)(5));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chbOpenOutput = new global::Gtk.CheckButton ();
			this.chbOpenOutput.CanFocus = true;
			this.chbOpenOutput.Name = "chbOpenOutput";
			this.chbOpenOutput.Label = global::Mono.Unix.Catalog.GetString ("Open output directory after publish");
			this.chbOpenOutput.Active = true;
			this.chbOpenOutput.DrawIndicator = true;
			this.chbOpenOutput.UseUnderline = true;
			this.table2.Add (this.chbOpenOutput);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbOpenOutput]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.XPadding = ((uint)(5));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chbPrecompile = new global::Gtk.CheckButton ();
			this.chbPrecompile.CanFocus = true;
			this.chbPrecompile.Name = "chbPrecompile";
			this.chbPrecompile.Label = global::Mono.Unix.Catalog.GetString ("Allow Background Compilation");
			this.chbPrecompile.DrawIndicator = true;
			this.chbPrecompile.UseUnderline = true;
			this.table2.Add (this.chbPrecompile);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbPrecompile]));
			w4.XPadding = ((uint)(5));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chbSaveAfterRun = new global::Gtk.CheckButton ();
			this.chbSaveAfterRun.CanFocus = true;
			this.chbSaveAfterRun.Name = "chbSaveAfterRun";
			this.chbSaveAfterRun.Label = global::Mono.Unix.Catalog.GetString ("Save changes before run / compile");
			this.chbSaveAfterRun.Active = true;
			this.chbSaveAfterRun.DrawIndicator = true;
			this.chbSaveAfterRun.UseUnderline = true;
			this.table2.Add (this.chbSaveAfterRun);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbSaveAfterRun]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.XPadding = ((uint)(5));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.chbShowError = new global::Gtk.CheckButton ();
			this.chbShowError.CanFocus = true;
			this.chbShowError.Name = "chbShowError";
			this.chbShowError.Label = global::Mono.Unix.Catalog.GetString ("Show Error Pane when Error Occured");
			this.chbShowError.DrawIndicator = true;
			this.chbShowError.UseUnderline = true;
			this.table2.Add (this.chbShowError);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.chbShowError]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XPadding = ((uint)(5));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
