
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Settings
{
	public partial class DirConditionsWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label5;
		private global::Gtk.Button button7;
		private global::Gtk.VBox vbMain;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Settings.DirConditionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Settings.DirConditionsWidget";
			// Container child Moscrif.IDE.Settings.DirConditionsWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Set Conditions for All Files in Directory");
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label5]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Apply to all files");
			this.hbox1.Add (this.button7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button7]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbMain = new global::Gtk.VBox ();
			this.vbMain.Name = "vbMain";
			this.vbMain.Spacing = 6;
			this.vbox2.Add (this.vbMain);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbMain]));
			w4.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		}
	}
}
