
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Settings
{
	public partial class ApplicationWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Table tblGlobal;
		private global::Gtk.Label label7;
		private global::Gtk.HSeparator hseparator1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Settings.ApplicationWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Settings.ApplicationWidget";
			// Container child Moscrif.IDE.Settings.ApplicationWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tblGlobal = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.tblGlobal.Name = "tblGlobal";
			this.tblGlobal.RowSpacing = ((uint)(6));
			this.tblGlobal.ColumnSpacing = ((uint)(6));
			// Container child tblGlobal.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.TooltipMarkup = "Pattern to be Used for Output Artefacts (Installation Files)";
			this.label7.WidthRequest = 75;
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Type :");
			this.tblGlobal.Add (this.label7);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tblGlobal [this.label7]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.tblGlobal);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tblGlobal]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
