
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Settings
{
	public partial class ResolutionOptionWidget
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tvResolution;
		private global::Gtk.VButtonBox vbuttonbox2;
		private global::Gtk.Button btnAddRules;
		private global::Gtk.Button btnDeleteRule;
		private global::Gtk.Button btnEditRule;
		private global::Gtk.Button button118;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Settings.ResolutionOptionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Settings.ResolutionOptionWidget";
			// Container child Moscrif.IDE.Settings.ResolutionOptionWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvResolution = new global::Gtk.TreeView ();
			this.tvResolution.CanFocus = true;
			this.tvResolution.Name = "tvResolution";
			this.GtkScrolledWindow.Add (this.tvResolution);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAddRules = new global::Gtk.Button ();
			this.btnAddRules.CanFocus = true;
			this.btnAddRules.Name = "btnAddRules";
			this.btnAddRules.UseUnderline = true;
			this.btnAddRules.Label = global::Mono.Unix.Catalog.GetString ("Add");
			this.vbuttonbox2.Add (this.btnAddRules);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnAddRules]));
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnDeleteRule = new global::Gtk.Button ();
			this.btnDeleteRule.CanFocus = true;
			this.btnDeleteRule.Name = "btnDeleteRule";
			this.btnDeleteRule.UseUnderline = true;
			this.btnDeleteRule.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			this.vbuttonbox2.Add (this.btnDeleteRule);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnDeleteRule]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditRule = new global::Gtk.Button ();
			this.btnEditRule.CanFocus = true;
			this.btnEditRule.Name = "btnEditRule";
			this.btnEditRule.UseUnderline = true;
			this.btnEditRule.Label = global::Mono.Unix.Catalog.GetString ("Edit");
			this.vbuttonbox2.Add (this.btnEditRule);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnEditRule]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button118 = new global::Gtk.Button ();
			this.button118.CanFocus = true;
			this.button118.Name = "button118";
			this.button118.UseUnderline = true;
			this.button118.Label = global::Mono.Unix.Catalog.GetString ("Default");
			this.vbuttonbox2.Add (this.button118);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.button118]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox1.Add (this.vbuttonbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.tvResolution.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTvResolutionRowActivated);
			this.btnAddRules.Clicked += new global::System.EventHandler (this.OnBtnAddRulesClicked);
			this.btnDeleteRule.Clicked += new global::System.EventHandler (this.OnBtnDeleteRuleClicked);
			this.btnEditRule.Clicked += new global::System.EventHandler (this.OnBtnEditRuleClicked);
			this.button118.Clicked += new global::System.EventHandler (this.OnButton118Clicked);
		}
	}
}
