
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Components
{
	public partial class LoginLogoutControl
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button btnState;
		private global::Gtk.Label label1;
		private global::Gtk.Label lblName;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Components.LoginLogoutControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Components.LoginLogoutControl";
			// Container child Moscrif.IDE.Components.LoginLogoutControl.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnState = new global::Gtk.Button ();
			this.btnState.CanFocus = true;
			this.btnState.Name = "btnState";
			this.btnState.UseUnderline = true;
			this.btnState.Relief = ((global::Gtk.ReliefStyle)(2));
			this.btnState.Label = global::Mono.Unix.Catalog.GetString ("Login");
			this.table1.Add (this.btnState);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnState]));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("Open Source");
			this.table1.Add (this.lblName);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblName]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnState.Clicked += new global::System.EventHandler (this.OnBtnStateClicked);
		}
	}
}
