
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Option
{
	public partial class ProxyWidget
	{
		private global::Gtk.Table tblMain;
		private global::Gtk.Frame frmProxyConfiguration;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table tbCustomlProxy;
		private global::Gtk.Entry entrName;
		private global::Gtk.Entry entrPassword;
		private global::Gtk.Entry entrProxy;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.SpinButton sbPort;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.RadioButton rbCustomProxy;
		private global::Gtk.RadioButton rbNoProxy;
		private global::Gtk.RadioButton rbSystemProxy;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Option.ProxyWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Option.ProxyWidget";
			// Container child Moscrif.IDE.Option.ProxyWidget.Gtk.Container+ContainerChild
			this.tblMain = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.tblMain.Name = "tblMain";
			this.tblMain.RowSpacing = ((uint)(6));
			this.tblMain.ColumnSpacing = ((uint)(6));
			// Container child tblMain.Gtk.Table+TableChild
			this.frmProxyConfiguration = new global::Gtk.Frame ();
			this.frmProxyConfiguration.Name = "frmProxyConfiguration";
			// Container child frmProxyConfiguration.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.tbCustomlProxy = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.tbCustomlProxy.Name = "tbCustomlProxy";
			this.tbCustomlProxy.RowSpacing = ((uint)(6));
			this.tbCustomlProxy.ColumnSpacing = ((uint)(6));
			this.tbCustomlProxy.BorderWidth = ((uint)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.entrName = new global::Gtk.Entry ();
			this.entrName.CanFocus = true;
			this.entrName.Name = "entrName";
			this.entrName.IsEditable = true;
			this.entrName.InvisibleChar = '●';
			this.tbCustomlProxy.Add (this.entrName);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.entrName]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XPadding = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.entrPassword = new global::Gtk.Entry ();
			this.entrPassword.CanFocus = true;
			this.entrPassword.Name = "entrPassword";
			this.entrPassword.IsEditable = true;
			this.entrPassword.InvisibleChar = '●';
			this.tbCustomlProxy.Add (this.entrPassword);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.entrPassword]));
			w2.TopAttach = ((uint)(3));
			w2.BottomAttach = ((uint)(4));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XPadding = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.entrProxy = new global::Gtk.Entry ();
			this.entrProxy.CanFocus = true;
			this.entrProxy.Name = "entrProxy";
			this.entrProxy.IsEditable = true;
			this.entrProxy.InvisibleChar = '●';
			this.tbCustomlProxy.Add (this.entrProxy);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.entrProxy]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XPadding = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Address :");
			this.tbCustomlProxy.Add (this.label1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.label1]));
			w4.YPadding = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Port :");
			this.tbCustomlProxy.Add (this.label2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.label2]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Name :");
			this.tbCustomlProxy.Add (this.label3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.label3]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password :");
			this.tbCustomlProxy.Add (this.label4);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.label4]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tbCustomlProxy.Gtk.Table+TableChild
			this.sbPort = new global::Gtk.SpinButton (0D, 1000000000D, 1D);
			this.sbPort.CanFocus = true;
			this.sbPort.Name = "sbPort";
			this.sbPort.Adjustment.PageIncrement = 10D;
			this.sbPort.ClimbRate = 1D;
			this.sbPort.Numeric = true;
			this.tbCustomlProxy.Add (this.sbPort);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tbCustomlProxy [this.sbPort]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XPadding = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.tbCustomlProxy);
			this.frmProxyConfiguration.Add (this.GtkAlignment);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Proxy Configuration</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frmProxyConfiguration.LabelWidget = this.GtkLabel3;
			this.tblMain.Add (this.frmProxyConfiguration);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblMain [this.frmProxyConfiguration]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.rbCustomProxy = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Manual proxy configuration"));
			this.rbCustomProxy.CanFocus = true;
			this.rbCustomProxy.Name = "rbCustomProxy";
			this.rbCustomProxy.DrawIndicator = true;
			this.rbCustomProxy.UseUnderline = true;
			this.rbCustomProxy.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.tblMain.Add (this.rbCustomProxy);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblMain [this.rbCustomProxy]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.rbNoProxy = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("No proxy"));
			this.rbNoProxy.CanFocus = true;
			this.rbNoProxy.Name = "rbNoProxy";
			this.rbNoProxy.DrawIndicator = true;
			this.rbNoProxy.UseUnderline = true;
			this.rbNoProxy.Group = this.rbCustomProxy.Group;
			this.tblMain.Add (this.rbNoProxy);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblMain [this.rbNoProxy]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMain.Gtk.Table+TableChild
			this.rbSystemProxy = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Use system proxy settings"));
			this.rbSystemProxy.CanFocus = true;
			this.rbSystemProxy.Name = "rbSystemProxy";
			this.rbSystemProxy.DrawIndicator = true;
			this.rbSystemProxy.UseUnderline = true;
			this.rbSystemProxy.Group = this.rbCustomProxy.Group;
			this.tblMain.Add (this.rbSystemProxy);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tblMain [this.rbSystemProxy]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tblMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.rbSystemProxy.Toggled += new global::System.EventHandler (this.OnRbSystemProxyToggled);
			this.rbNoProxy.Toggled += new global::System.EventHandler (this.OnRbNoProxyToggled);
			this.rbCustomProxy.Toggled += new global::System.EventHandler (this.OnRbCustomProxyToggled);
		}
	}
}
