
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Controls
{
	public partial class ApplicationFileControl
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button btnManage;
		private global::Gtk.ComboBox cbOrientation;
		private global::Gtk.Entry entAuthor;
		private global::Gtk.Entry entCopyright;
		private global::Gtk.Entry entDescription;
		private global::Gtk.Entry entHomepage;
		private global::Gtk.Entry entTitle;
		private global::Gtk.Entry entUses;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label lblName2;
		private global::Gtk.Table tblVersion;
		private global::Gtk.Entry entrVersionMajor;
		private global::Gtk.Entry entrVersionMinor;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label label1;
		private global::Gtk.Label Uses;
		private global::Gtk.Label Uses1;
		private global::Gtk.Label Uses2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Controls.ApplicationFileControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Controls.ApplicationFileControl";
			// Container child Moscrif.IDE.Controls.ApplicationFileControl.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(11)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnManage = new global::Gtk.Button ();
			this.btnManage.CanFocus = true;
			this.btnManage.Name = "btnManage";
			this.btnManage.UseUnderline = true;
			this.btnManage.Label = global::Mono.Unix.Catalog.GetString ("Manage Libs");
			this.table1.Add (this.btnManage);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnManage]));
			w1.TopAttach = ((uint)(7));
			w1.BottomAttach = ((uint)(8));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbOrientation = global::Gtk.ComboBox.NewText ();
			this.cbOrientation.Name = "cbOrientation";
			this.table1.Add (this.cbOrientation);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbOrientation]));
			w2.TopAttach = ((uint)(8));
			w2.BottomAttach = ((uint)(9));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entAuthor = new global::Gtk.Entry ();
			this.entAuthor.CanFocus = true;
			this.entAuthor.Name = "entAuthor";
			this.entAuthor.IsEditable = true;
			this.entAuthor.InvisibleChar = '●';
			this.table1.Add (this.entAuthor);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.entAuthor]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(3));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entCopyright = new global::Gtk.Entry ();
			this.entCopyright.CanFocus = true;
			this.entCopyright.Name = "entCopyright";
			this.entCopyright.IsEditable = true;
			this.entCopyright.InvisibleChar = '●';
			this.table1.Add (this.entCopyright);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.entCopyright]));
			w4.TopAttach = ((uint)(5));
			w4.BottomAttach = ((uint)(6));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entDescription = new global::Gtk.Entry ();
			this.entDescription.CanFocus = true;
			this.entDescription.Name = "entDescription";
			this.entDescription.IsEditable = true;
			this.entDescription.InvisibleChar = '●';
			this.table1.Add (this.entDescription);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.entDescription]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(3));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entHomepage = new global::Gtk.Entry ();
			this.entHomepage.CanFocus = true;
			this.entHomepage.Name = "entHomepage";
			this.entHomepage.IsEditable = true;
			this.entHomepage.InvisibleChar = '●';
			this.table1.Add (this.entHomepage);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.entHomepage]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(3));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entTitle = new global::Gtk.Entry ();
			this.entTitle.WidthRequest = 344;
			this.entTitle.CanFocus = true;
			this.entTitle.Name = "entTitle";
			this.entTitle.IsEditable = true;
			this.entTitle.InvisibleChar = '●';
			this.table1.Add (this.entTitle);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.entTitle]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(3));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entUses = new global::Gtk.Entry ();
			this.entUses.CanFocus = true;
			this.entUses.Name = "entUses";
			this.entUses.IsEditable = true;
			this.entUses.InvisibleChar = '●';
			this.table1.Add (this.entUses);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.entUses]));
			w8.TopAttach = ((uint)(7));
			w8.BottomAttach = ((uint)(8));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 75;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name :");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 75;
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Title :");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 75;
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Description :");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 75;
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Author :");
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 75;
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Copyright :");
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 75;
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Homepage :");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w14.TopAttach = ((uint)(6));
			w14.BottomAttach = ((uint)(7));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblName2 = new global::Gtk.Label ();
			this.lblName2.Name = "lblName2";
			this.lblName2.Xalign = 0F;
			this.lblName2.LabelProp = global::Mono.Unix.Catalog.GetString ("label18");
			this.table1.Add (this.lblName2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblName2]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tblVersion = new global::Gtk.Table (((uint)(1)), ((uint)(6)), false);
			this.tblVersion.Name = "tblVersion";
			this.tblVersion.RowSpacing = ((uint)(6));
			this.tblVersion.ColumnSpacing = ((uint)(6));
			// Container child tblVersion.Gtk.Table+TableChild
			this.entrVersionMajor = new global::Gtk.Entry ();
			this.entrVersionMajor.WidthRequest = 45;
			this.entrVersionMajor.CanFocus = true;
			this.entrVersionMajor.Name = "entrVersionMajor";
			this.entrVersionMajor.IsEditable = true;
			this.entrVersionMajor.InvisibleChar = '●';
			this.tblVersion.Add (this.entrVersionMajor);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblVersion [this.entrVersionMajor]));
			w16.XOptions = ((global::Gtk.AttachOptions)(0));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblVersion.Gtk.Table+TableChild
			this.entrVersionMinor = new global::Gtk.Entry ();
			this.entrVersionMinor.WidthRequest = 45;
			this.entrVersionMinor.CanFocus = true;
			this.entrVersionMinor.Name = "entrVersionMinor";
			this.entrVersionMinor.IsEditable = true;
			this.entrVersionMinor.InvisibleChar = '●';
			this.tblVersion.Add (this.entrVersionMinor);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblVersion [this.entrVersionMinor]));
			w17.LeftAttach = ((uint)(3));
			w17.RightAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(0));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblVersion.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.tblVersion.Add (this.fixed1);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblVersion [this.fixed1]));
			w18.LeftAttach = ((uint)(5));
			w18.RightAttach = ((uint)(6));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblVersion.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>.</b>");
			this.label1.UseMarkup = true;
			this.tblVersion.Add (this.label1);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblVersion [this.label1]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add (this.tblVersion);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.tblVersion]));
			w20.TopAttach = ((uint)(9));
			w20.BottomAttach = ((uint)(10));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.Uses = new global::Gtk.Label ();
			this.Uses.WidthRequest = 75;
			this.Uses.Name = "Uses";
			this.Uses.Xalign = 1F;
			this.Uses.LabelProp = global::Mono.Unix.Catalog.GetString ("Uses :");
			this.table1.Add (this.Uses);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.Uses]));
			w21.TopAttach = ((uint)(7));
			w21.BottomAttach = ((uint)(8));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.Uses1 = new global::Gtk.Label ();
			this.Uses1.WidthRequest = 75;
			this.Uses1.Name = "Uses1";
			this.Uses1.Xalign = 1F;
			this.Uses1.LabelProp = global::Mono.Unix.Catalog.GetString ("Version :");
			this.table1.Add (this.Uses1);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.Uses1]));
			w22.TopAttach = ((uint)(9));
			w22.BottomAttach = ((uint)(10));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.Uses2 = new global::Gtk.Label ();
			this.Uses2.WidthRequest = 75;
			this.Uses2.Name = "Uses2";
			this.Uses2.Xalign = 1F;
			this.Uses2.LabelProp = global::Mono.Unix.Catalog.GetString ("Orientation :");
			this.table1.Add (this.Uses2);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.Uses2]));
			w23.TopAttach = ((uint)(8));
			w23.BottomAttach = ((uint)(9));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnManage.Clicked += new global::System.EventHandler (this.OnBtnManageClicked);
		}
	}
}
