
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Components
{
	public partial class SkinThemeControl
	{
		private global::Gtk.Table table1;
		private global::Gtk.ComboBox cbSkin;
		private global::Gtk.ComboBox cbTheme;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Components.SkinThemeControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Components.SkinThemeControl";
			// Container child Moscrif.IDE.Components.SkinThemeControl.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(5));
			this.table1.ColumnSpacing = ((uint)(8));
			this.table1.BorderWidth = ((uint)(8));
			// Container child table1.Gtk.Table+TableChild
			this.cbSkin = global::Gtk.ComboBox.NewText ();
			this.cbSkin.Name = "cbSkin";
			this.table1.Add (this.cbSkin);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbSkin]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbTheme = global::Gtk.ComboBox.NewText ();
			this.cbTheme.Name = "cbTheme";
			this.table1.Add (this.cbTheme);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbTheme]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.TooltipMarkup = "Skin to be Embeded into Output Installation";
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Skin :");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.TooltipMarkup = "Theme to be Aplied";
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Theme :");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
