
// This file has been generated by the GUI designer. Do not modify.
namespace Moscrif.IDE.Components
{
	public partial class StartEventControl
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.Table table1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Table tblAction;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Frame frame2;
		private global::Gtk.Table tblRecentWork;
		private global::Gtk.Label GtkLabel5;
		private global::Gtk.Frame frmRss;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.Table tblRss;
		private global::Gtk.Button btnRssLoad;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Frame frmSamples;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Table tblSamples;
		private global::Gtk.HBox hbMorSample;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.Frame frmTweet;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Table tblTwitt;
		private global::Gtk.Button btnTwitLoad;
		private global::Gtk.Label GtkLabel6;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Moscrif.IDE.Components.StartEventControl
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Moscrif.IDE.Components.StartEventControl";
			// Container child Moscrif.IDE.Components.StartEventControl.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(4));
			// Container child hbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.tblAction = new global::Gtk.Table (((uint)(5)), ((uint)(1)), false);
			this.tblAction.Name = "tblAction";
			this.tblAction.RowSpacing = ((uint)(6));
			this.tblAction.ColumnSpacing = ((uint)(6));
			this.frame1.Add (this.tblAction);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.Xalign = 0F;
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Action</u></b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.table1.Add (this.frame1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame1]));
			w2.XPadding = ((uint)(3));
			w2.YPadding = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.tblRecentWork = new global::Gtk.Table (((uint)(6)), ((uint)(1)), false);
			this.tblRecentWork.Name = "tblRecentWork";
			this.tblRecentWork.RowSpacing = ((uint)(6));
			this.tblRecentWork.ColumnSpacing = ((uint)(6));
			this.frame2.Add (this.tblRecentWork);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Recent Workspaces</u></b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel5;
			this.table1.Add (this.frame2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XPadding = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.frmRss = new global::Gtk.Frame ();
			this.frmRss.Name = "frmRss";
			this.frmRss.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frmRss.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.tblRss = new global::Gtk.Table (((uint)(6)), ((uint)(1)), false);
			this.tblRss.Name = "tblRss";
			this.tblRss.RowSpacing = ((uint)(6));
			this.tblRss.ColumnSpacing = ((uint)(6));
			// Container child tblRss.Gtk.Table+TableChild
			this.btnRssLoad = new global::Gtk.Button ();
			this.btnRssLoad.WidthRequest = 250;
			this.btnRssLoad.Sensitive = false;
			this.btnRssLoad.CanFocus = true;
			this.btnRssLoad.Name = "btnRssLoad";
			this.btnRssLoad.UseUnderline = true;
			this.btnRssLoad.Relief = ((global::Gtk.ReliefStyle)(2));
			this.btnRssLoad.Label = "";
			this.tblRss.Add (this.btnRssLoad);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblRss [this.btnRssLoad]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.tblRss);
			this.frmRss.Add (this.GtkAlignment3);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>RSS</u></b>");
			this.GtkLabel7.UseMarkup = true;
			this.frmRss.LabelWidget = this.GtkLabel7;
			this.table1.Add (this.frmRss);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.frmRss]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.frmSamples = new global::Gtk.Frame ();
			this.frmSamples.WidthRequest = 250;
			this.frmSamples.Name = "frmSamples";
			this.frmSamples.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frmSamples.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tblSamples = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.tblSamples.Name = "tblSamples";
			this.tblSamples.RowSpacing = ((uint)(6));
			this.tblSamples.ColumnSpacing = ((uint)(6));
			this.vbox2.Add (this.tblSamples);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tblSamples]));
			w9.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbMorSample = new global::Gtk.HBox ();
			this.hbMorSample.Name = "hbMorSample";
			this.hbMorSample.Spacing = 6;
			this.vbox2.Add (this.hbMorSample);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbMorSample]));
			w10.Position = 1;
			this.GtkAlignment4.Add (this.vbox2);
			this.frmSamples.Add (this.GtkAlignment4);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Samples</u></b>");
			this.GtkLabel8.UseMarkup = true;
			this.frmSamples.LabelWidget = this.GtkLabel8;
			this.table1.Add (this.frmSamples);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.frmSamples]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YPadding = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.table1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frmTweet = new global::Gtk.Frame ();
			this.frmTweet.Name = "frmTweet";
			this.frmTweet.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frmTweet.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.tblTwitt = new global::Gtk.Table (((uint)(6)), ((uint)(1)), false);
			this.tblTwitt.Name = "tblTwitt";
			this.tblTwitt.RowSpacing = ((uint)(6));
			this.tblTwitt.ColumnSpacing = ((uint)(6));
			// Container child tblTwitt.Gtk.Table+TableChild
			this.btnTwitLoad = new global::Gtk.Button ();
			this.btnTwitLoad.WidthRequest = 250;
			this.btnTwitLoad.Sensitive = false;
			this.btnTwitLoad.CanFocus = true;
			this.btnTwitLoad.Name = "btnTwitLoad";
			this.btnTwitLoad.UseUnderline = true;
			this.btnTwitLoad.Relief = ((global::Gtk.ReliefStyle)(2));
			this.btnTwitLoad.Label = "";
			this.tblTwitt.Add (this.btnTwitLoad);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblTwitt [this.btnTwitLoad]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.tblTwitt);
			this.frmTweet.Add (this.GtkAlignment2);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b><u>Twitter</u></b>");
			this.GtkLabel6.UseMarkup = true;
			this.frmTweet.LabelWidget = this.GtkLabel6;
			this.hbox2.Add (this.frmTweet);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frmTweet]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.frmRss.Hide ();
			this.Hide ();
		}
	}
}
