using System;


namespace Moscrif.IDE.Editors
{
	public enum EditorComands
	{
		SourceEditor_togglebookmark,
		SourceEditor_clearbookmark,
		SourceEditor_nextbookmark,
		SourceEditor_previousbookmark,
		DeleteRightChar,
		CharLeft,
		CharRight,
		LineUp,
		LineDown,
		DocumentStart,
		DocumentEnd,
		PageUp,
		PageDown,
		ScrollLineUp,
		ScrollLineDown,
		ScrollPageUp,
		ScrollPageDown,
		DeleteLine,
		DeleteToLineEnd,
		MoveBlockUp,
		MoveBlockDown,
		ShowParameterCompletionWindow,
		GotoMatchingBrace,
		SelectionMoveLeft,
		SelectionMoveRight,
		MovePrevWord,
		MoveNextWord,
		SelectionMovePrevWord,
		SelectionMoveNextWord,
		SelectionMoveUp,
		SelectionMoveDown,
		SelectionMoveHome,
		SelectionMoveEnd,
		SelectionMoveToDocumentStart,
		SelectionMoveToDocumentEnd,
		SwitchCaretMode,
		InsertTab,
		RemoveTab,
		InsertNewLine,
		InsertNewLinePreserveCaretPosition,
		InsertNewLineAtEnd,
		CompleteStatement,
		DeletePrevWord,
		DeleteNextWord,
		SelectionPageDownAction,
		SelectionPageUpAction,
		MovePrevSubword,
		MoveNextSubword,
		SelectionMovePrevSubword,
		SelectionMoveNextSubword,
		DeletePrevSubword,
		DeleteNextSubword,
		TransposeCharacters,
		RecenterEditor
	}
}

